package com.kingo.apps.repository;

import com.kingo.apps.entity.Active;

import java.util.List;
import java.util.Map;

public interface ActiveMapper {

    /**
     * 按日分组累计
     * @param sdate
     * @param edate
     * @return
     */
    public List<Map<String, Object>> finfByChart(String sdate, String edate);

    /**
     * 按日分组累计和产品广告位
     * @param sdate
     * @param edate
     * @param chapp
     * @return
     */
    public List<Map<String, Object>> finfByChartChapp(String sdate, String edate, String chapp);

    /**
     * 按日期查询
     * @return
     */
    List<Active> findByDate(String sdate, String edate);

    /**
     * 按日期和产品广告位查询
     * @return
     */
    List<Active> findByDateAndChapp(String sdate, String edate, String chapp);

    /**
     * 按广告位查询
     * @return
     */
    List<Active> findByChapp(String chapp);

    /**
     * 查询全部
     * @return
     */
    List<Active> findAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kingo_active_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kingo_active_detail
     *
     * @mbggenerated
     */
    int insert(Active record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kingo_active_detail
     *
     * @mbggenerated
     */
    int insertSelective(Active record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kingo_active_detail
     *
     * @mbggenerated
     */
    Active selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kingo_active_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Active record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kingo_active_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Active record);
}