package com.kingo.apps.entity;

import java.util.Date;

public class Active {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kingo_active_detail.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kingo_active_detail.curl
     *
     * @mbggenerated
     */
    private String curl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kingo_active_detail.cofferid
     *
     * @mbggenerated
     */
    private String cofferid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kingo_active_detail.cprice
     *
     * @mbggenerated
     */
    private Double cprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kingo_active_detail.caffsub
     *
     * @mbggenerated
     */
    private String caffsub;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kingo_active_detail.cgaid
     *
     * @mbggenerated
     */
    private String cgaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kingo_active_detail.insertdate
     *
     * @mbggenerated
     */
    private Date insertdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kingo_active_detail.id
     *
     * @return the value of kingo_active_detail.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kingo_active_detail.id
     *
     * @param id the value for kingo_active_detail.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kingo_active_detail.curl
     *
     * @return the value of kingo_active_detail.curl
     *
     * @mbggenerated
     */
    public String getCurl() {
        return curl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kingo_active_detail.curl
     *
     * @param curl the value for kingo_active_detail.curl
     *
     * @mbggenerated
     */
    public void setCurl(String curl) {
        this.curl = curl == null ? null : curl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kingo_active_detail.cofferid
     *
     * @return the value of kingo_active_detail.cofferid
     *
     * @mbggenerated
     */
    public String getCofferid() {
        return cofferid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kingo_active_detail.cofferid
     *
     * @param cofferid the value for kingo_active_detail.cofferid
     *
     * @mbggenerated
     */
    public void setCofferid(String cofferid) {
        this.cofferid = cofferid == null ? null : cofferid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kingo_active_detail.cprice
     *
     * @return the value of kingo_active_detail.cprice
     *
     * @mbggenerated
     */
    public Double getCprice() {
        return cprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kingo_active_detail.cprice
     *
     * @param cprice the value for kingo_active_detail.cprice
     *
     * @mbggenerated
     */
    public void setCprice(Double cprice) {
        this.cprice = cprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kingo_active_detail.caffsub
     *
     * @return the value of kingo_active_detail.caffsub
     *
     * @mbggenerated
     */
    public String getCaffsub() {
        return caffsub;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kingo_active_detail.caffsub
     *
     * @param caffsub the value for kingo_active_detail.caffsub
     *
     * @mbggenerated
     */
    public void setCaffsub(String caffsub) {
        this.caffsub = caffsub == null ? null : caffsub.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kingo_active_detail.cgaid
     *
     * @return the value of kingo_active_detail.cgaid
     *
     * @mbggenerated
     */
    public String getCgaid() {
        return cgaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kingo_active_detail.cgaid
     *
     * @param cgaid the value for kingo_active_detail.cgaid
     *
     * @mbggenerated
     */
    public void setCgaid(String cgaid) {
        this.cgaid = cgaid == null ? null : cgaid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kingo_active_detail.insertdate
     *
     * @return the value of kingo_active_detail.insertdate
     *
     * @mbggenerated
     */
    public Date getInsertdate() {
        return insertdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kingo_active_detail.insertdate
     *
     * @param insertdate the value for kingo_active_detail.insertdate
     *
     * @mbggenerated
     */
    public void setInsertdate(Date insertdate) {
        this.insertdate = insertdate;
    }
}