package com.kingo.apps.entity;


import org.hibernate.validator.constraints.Length;

import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import java.util.Date;

public class Users {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kingo_users.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kingo_users.username
     *
     * @mbggenerated
     */
    @NotNull(message = "用户名不能为空")
    @Length(min = 2, max = 20, message = "用户名长度必须在2~20之间!")
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kingo_users.password
     *
     * @mbggenerated
     */
    @NotNull(message = "密码不能为空")
    @Length(min = 2, max = 20, message = "密码长度必须在6~30之间!")
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kingo_users.headurl
     *
     * @mbggenerated
     */
    private String headurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kingo_users.realname
     *
     * @mbggenerated
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kingo_users.phonenumber
     *
     * @mbggenerated
     */
    private Integer phonenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kingo_users.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kingo_users.sex
     *
     * @mbggenerated
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kingo_users.gistime
     *
     * @mbggenerated
     */
    private Date gistime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kingo_users.id
     *
     * @return the value of kingo_users.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kingo_users.id
     *
     * @param id the value for kingo_users.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kingo_users.username
     *
     * @return the value of kingo_users.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kingo_users.username
     *
     * @param username the value for kingo_users.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kingo_users.password
     *
     * @return the value of kingo_users.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kingo_users.password
     *
     * @param password the value for kingo_users.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kingo_users.headurl
     *
     * @return the value of kingo_users.headurl
     *
     * @mbggenerated
     */
    public String getHeadurl() {
        return headurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kingo_users.headurl
     *
     * @param headurl the value for kingo_users.headurl
     *
     * @mbggenerated
     */
    public void setHeadurl(String headurl) {
        this.headurl = headurl == null ? null : headurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kingo_users.realname
     *
     * @return the value of kingo_users.realname
     *
     * @mbggenerated
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kingo_users.realname
     *
     * @param realname the value for kingo_users.realname
     *
     * @mbggenerated
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kingo_users.phonenumber
     *
     * @return the value of kingo_users.phonenumber
     *
     * @mbggenerated
     */
    public Integer getPhonenumber() {
        return phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kingo_users.phonenumber
     *
     * @param phonenumber the value for kingo_users.phonenumber
     *
     * @mbggenerated
     */
    public void setPhonenumber(Integer phonenumber) {
        this.phonenumber = phonenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kingo_users.email
     *
     * @return the value of kingo_users.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kingo_users.email
     *
     * @param email the value for kingo_users.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kingo_users.sex
     *
     * @return the value of kingo_users.sex
     *
     * @mbggenerated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kingo_users.sex
     *
     * @param sex the value for kingo_users.sex
     *
     * @mbggenerated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kingo_users.gistime
     *
     * @return the value of kingo_users.gistime
     *
     * @mbggenerated
     */
    public Date getGistime() {
        return gistime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kingo_users.gistime
     *
     * @param gistime the value for kingo_users.gistime
     *
     * @mbggenerated
     */
    public void setGistime(Date gistime) {
        this.gistime = gistime;
    }
}